USE Olympics_21936856;

INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 800m Freestyle', 'SWM', 'Swimming', '2024-07-29', 'Men''s 800m Freestyle - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Four', 'ROW', 'Rowing', '2024-07-28', 'Men''s Four Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'FBL', 'Football', '2024-07-27', 'Men''s Group D');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'HOC', 'Hockey', '2024-07-31', 'Men''s Pool A');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Keirin', 'CTR', 'Cycling Track', '2024-08-08', 'Women''s Keirin, Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 66kg', 'BOX', 'Boxing', '2024-08-06', 'Women''s 66kg - Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 400m Freestyle', 'SWM', 'Swimming', '2024-07-27', 'Women''s 400m Freestyle - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Kayak Single', 'CSL', 'Canoe Slalom', '2024-07-27', 'Women''s Kayak Single Hts 1st and 2nd Run');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 100m Hurdles', 'ATH', 'Athletics', '2024-08-08', 'Women''s 100m Hurdles Repechage Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Individual', 'ARC', 'Archery', '2024-08-04', 'Men''s Individual Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 10m Platform', 'DIV', 'Diving', '2024-08-06', 'Women''s 10m Platform Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed Multihull', 'SAL', 'Sailing', '2024-08-05', 'Mixed Multihull Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('B-Boys', 'BKG', 'Breaking', '2024-08-10', 'B-Boys Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Singles', 'BDM', 'Badminton', '2024-07-31', 'Men''s Singles Group Play Stage - Grp D');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'VVO', 'Volleyball', '2024-07-31', 'Men''s Preliminary Round - Pool C');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -63 kg', 'JUD', 'Judo', '2024-07-30', 'Women -63 kg Contests for Bronze Medals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Team', 'TTE', 'Table Tennis', '2024-08-07', 'Men''s Team Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Single Sculls', 'ROW', 'Rowing', '2024-08-01', 'Men''s Single Sculls Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Rings', 'GAR', 'Artistic Gymnastics', '2024-08-04', 'Men''s Rings Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'RU7', 'Rugby Sevens', '2024-07-29', 'Women''s Pool A');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Foil Individual', 'FEN', 'Fencing', '2024-07-29', 'Men''s Foil Individual Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men +100 kg', 'JUD', 'Judo', '2024-08-02', 'Men +100 kg Repechage');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -100 kg', 'JUD', 'Judo', '2024-08-01', 'Men -100 kg Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Canoe Single', 'CSL', 'Canoe Slalom', '2024-07-31', 'Women''s Canoe Single Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Eventing Individual', 'EQU', 'Equestrian', '2024-07-28', 'Eventing Individual Cross Country');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Freestyle 68kg', 'WRE', 'Wrestling', '2024-08-06', 'WFS 68kg Repechage');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Singles', 'TTE', 'Table Tennis', '2024-07-27', 'Men''s Singles Preliminary Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Ã‰pÃ©e Team', 'FEN', 'Fencing', '2024-07-30', 'Women''s Ã‰pÃ©e Team Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 4 x 200m Freestyle Relay', 'SWM', 'Swimming', '2024-08-01', 'Women''s 4 x 200m Freestyle Relay - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'SRF', 'Surfing', '2024-08-05', 'Women''s Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Individual', 'MPN', 'Modern Pentathlon', '2024-08-10', 'Men''s Individual Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Individual All-Around', 'GRY', 'Rhythmic Gymnastics', '2024-08-09', 'Individual All-Around Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Kite', 'SAL', 'Sailing', '2024-08-06', 'Men''s Kite Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Sabre Individual', 'FEN', 'Fencing', '2024-07-27', 'Men''s Sabre Individual Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Lightweight Men''s Double Sculls', 'ROW', 'Rowing', '2024-07-31', 'LWT Men''s Double Sculls Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('10m Air Rifle Men', 'SHO', 'Shooting', '2024-07-27', '10m Air Rifle Men''s Training');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Skeet Mixed Team', 'SHO', 'Shooting', '2024-08-05', 'Skeet Mixed Team Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('B-Girls', 'BKG', 'Breaking', '2024-08-09', 'B-Girls Round Robin - Group A');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Singles', 'BDM', 'Badminton', '2024-07-31', 'Women''s Singles Group Play Stage - Grp K');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 1500m Freestyle', 'SWM', 'Swimming', '2024-08-04', 'Men''s 1500m Freestyle Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'WPO', 'Water Polo', '2024-08-09', 'Men''s Classification 5th-8th');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 100m Freestyle', 'SWM', 'Swimming', '2024-07-31', 'Women''s 100m Freestyle Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'BKB', 'Basketball', '2024-07-29', 'Women''s Group Phase - Group C');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Doubles', 'BDM', 'Badminton', '2024-07-28', 'Men''s Doubles Group Play Stage - Grp D');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -78 kg', 'JUD', 'Judo', '2024-08-01', 'Women -78 kg Elimination Round of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -52 kg', 'JUD', 'Judo', '2024-07-28', 'Women -52 kg Elimination Round of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -48 kg', 'JUD', 'Judo', '2024-07-27', 'Women -48 kg Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'VBV', 'Beach Volleyball', '2024-08-07', 'Women''s Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'HOC', 'Hockey', '2024-08-01', 'Women''s Pool A');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 71kg', 'BOX', 'Boxing', '2024-08-09', 'Men''s 71kg - Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Individual Stroke Play', 'GLF', 'Golf', '2024-08-08', 'Women''s Individual Stroke Play');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Long Jump', 'ATH', 'Athletics', '2024-08-06', 'Women''s Long Jump Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 4 x 100m Medley Relay', 'SWM', 'Swimming', '2024-08-04', 'Women''s 4 x 100m Medley Relay Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 200m Butterfly', 'SWM', 'Swimming', '2024-07-31', 'Women''s 200m Butterfly Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('10m Air Pistol Mixed Team', 'SHO', 'Shooting', '2024-07-29', '10m Air Pistol Mixed Team Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'WPO', 'Water Polo', '2024-08-08', 'Women''s Classification 5th-8th');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 100m', 'ATH', 'Athletics', '2024-08-03', 'Women''s 100m Semi-Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 1500m', 'ATH', 'Athletics', '2024-08-04', 'Men''s 1500m Semi-Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'HBL', 'Handball', '2024-08-02', 'Men''s Preliminary Round Group B');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Team', 'TTE', 'Table Tennis', '2024-08-06', 'Women''s Team Round of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'FBL', 'Football', '2024-07-25', 'Women''s Group B');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 51kg', 'BOX', 'Boxing', '2024-08-04', 'Men''s 51kg - Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'BK3', '3x3 Basketball', '2024-07-31', 'Women''s Pool Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 100m', 'ATH', 'Athletics', '2024-08-04', 'Men''s 100m Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Doubles', 'TEN', 'Tennis', '2024-07-28', 'Women''s Doubles First Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women +67kg', 'TKW', 'Taekwondo', '2024-08-10', 'Women +67kg Gold Medal Contest');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Foil Team', 'FEN', 'Fencing', '2024-08-04', 'Men''s Foil Team Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Trap Men', 'SHO', 'Shooting', '2024-07-28', 'Trap Men''s Training');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 54kg', 'BOX', 'Boxing', '2024-08-04', 'Women''s 54kg - Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Team Sprint', 'CTR', 'Cycling Track', '2024-08-05', 'Women''s Team Sprint, First Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 63.5kg', 'BOX', 'Boxing', '2024-08-04', 'Men''s 63.5kg - Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -57 kg', 'JUD', 'Judo', '2024-07-29', 'Women -57 kg Repechage');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 5000m', 'ATH', 'Athletics', '2024-08-10', 'Men''s 5000m Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed Doubles', 'BDM', 'Badminton', '2024-07-27', 'Mixed Doubles Group Play Stage - Grp D');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Kayak Single 500m', 'CSP', 'Canoe Sprint', '2024-08-10', 'Women''s Kayak Single 500m Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Foil Team', 'FEN', 'Fencing', '2024-08-01', 'Women''s Foil Team Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'VBV', 'Beach Volleyball', '2024-08-01', 'Men''s Preliminary - Pool A - Matches');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -49kg', 'TKW', 'Taekwondo', '2024-08-07', 'Women -49kg Repechages');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Team Sprint', 'CTR', 'Cycling Track', '2024-08-05', 'Men''s Team Sprint, Qualifying');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 3m Springboard', 'DIV', 'Diving', '2024-08-08', 'Women''s 3m Springboard Semifinal');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Speed', 'CLB', 'Sport Climbing', '2024-08-08', 'Men''s Speed Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Decathlon', 'ATH', 'Athletics', '2024-08-03', 'Men''s Decathlon 1500m');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men +80kg', 'TKW', 'Taekwondo', '2024-08-10', 'Men +80kg Round of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Eight', 'ROW', 'Rowing', '2024-08-03', 'Women''s Eight Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 89kg', 'WLF', 'Weightlifting', '2024-08-09', 'Men''s 89kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 200m Breaststroke', 'SWM', 'Swimming', '2024-08-01', 'Women''s 200m Breaststroke Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Discus Throw', 'ATH', 'Athletics', '2024-08-07', 'Men''s Discus Throw Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Freestyle 57kg', 'WRE', 'Wrestling', '2024-08-08', 'MFS 57kg Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Lightweight Women''s Double Sculls', 'ROW', 'Rowing', '2024-07-31', 'LWT Women''s Double Sculls Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 200m Freestyle', 'SWM', 'Swimming', '2024-07-29', 'Women''s 200m Freestyle Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -73 kg', 'JUD', 'Judo', '2024-07-29', 'Men -73 kg Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women +78 kg', 'JUD', 'Judo', '2024-08-02', 'Women +78 kg Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'BKB', 'Basketball', '2024-08-03', 'Men''s Group Phase - Group C');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -90 kg', 'JUD', 'Judo', '2024-07-31', 'Men -90 kg Elimination Round of 32');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 4 x 100m Medley Relay', 'SWM', 'Swimming', '2024-08-03', 'Men''s 4 x 100m Medley Relay - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed Doubles', 'TTE', 'Table Tennis', '2024-07-29', 'Mixed Doubles Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Freestyle 97kg', 'WRE', 'Wrestling', '2024-08-11', 'MFS 97kg Bronze Medal Matches');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Freestyle 65kg', 'WRE', 'Wrestling', '2024-08-11', 'MFS 65kg Repechage');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Boulder & Lead', 'CLB', 'Sport Climbing', '2024-08-10', 'Women''s Boulder & Lead Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Single Sculls', 'ROW', 'Rowing', '2024-07-30', 'Women''s Single Sculls Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Individual', 'TRI', 'Triathlon', '2024-07-31', 'Men''s Individual');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Marathon Race Walk Relay Mixed', 'ATH', 'Athletics', '2024-08-07', 'Marathon Race Walk Relay Mixed');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Quadruple Sculls', 'ROW', 'Rowing', '2024-07-27', 'Men''s Quad. Sculls Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -70 kg', 'JUD', 'Judo', '2024-07-31', 'Women -70 kg Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Windsurfing', 'SAL', 'Sailing', '2024-07-30', 'Men''s Windsurfing Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 80kg', 'BOX', 'Boxing', '2024-08-07', 'Men''s 80kg - Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Skiff', 'SAL', 'Sailing', '2024-07-29', 'Men''s Skiff Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed Relay', 'TRI', 'Triathlon', '2024-08-05', 'Mixed Relay');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'RU7', 'Rugby Sevens', '2024-07-27', 'Men''s Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Individual Stroke Play', 'GLF', 'Golf', '2024-08-02', 'Men''s Individual Stroke Play');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Sabre Individual', 'FEN', 'Fencing', '2024-07-29', 'Women''s Sabre Individual Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'BK3', '3x3 Basketball', '2024-08-02', 'Men''s Pool Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -81 kg', 'JUD', 'Judo', '2024-07-30', 'Men -81 kg Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed Team', 'JUD', 'Judo', '2024-08-03', 'Mixed Team Repechage');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Canoe Double 500m', 'CSP', 'Canoe Sprint', '2024-08-08', 'Men''s Canoe Double 500m Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Canoe Single 200m', 'CSP', 'Canoe Sprint', '2024-08-08', 'Women''s Canoe Single 200m Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'HBL', 'Handball', '2024-08-01', 'Women''s Preliminary Round Group A');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 50m Freestyle', 'SWM', 'Swimming', '2024-08-03', 'Women''s 50m Freestyle - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Greco-Roman 97kg', 'WRE', 'Wrestling', '2024-08-06', 'MGR 97kg Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 100m Butterfly', 'SWM', 'Swimming', '2024-08-02', 'Men''s 100m Butterfly Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'BMX', 'Cycling BMX Racing', '2024-08-01', 'Men, Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Dressage Team', 'EQU', 'Equestrian', '2024-07-31', 'Dressage Team Grand Prix');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Doubles', 'TEN', 'Tennis', '2024-07-30', 'Men''s Doubles Second Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 100m Breaststroke', 'SWM', 'Swimming', '2024-07-28', 'Men''s 100m Breaststroke Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Team', 'SWA', 'Artistic Swimming', '2024-08-06', 'Team Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Double Sculls', 'ROW', 'Rowing', '2024-07-27', 'Men''s Double Sculls Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'VVO', 'Volleyball', '2024-08-08', 'Women''s Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Doubles', 'BDM', 'Badminton', '2024-07-27', 'Women''s Doubles Group Play Stage - Grp B');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Dinghy', 'SAL', 'Sailing', '2024-08-05', 'Men''s Dinghy Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Street', 'SKB', 'Skateboarding', '2024-07-28', 'Women''s Street Prelims');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Freestyle 74kg', 'WRE', 'Wrestling', '2024-08-10', 'MFS 74kg Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 75kg', 'BOX', 'Boxing', '2024-07-31', 'Women''s 75kg - Prelims - Round of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 200m', 'ATH', 'Athletics', '2024-08-04', 'Women''s 200m Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'BMX', 'Cycling BMX Racing', '2024-08-01', 'Women, Last Chance Race');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s All-Around', 'GAR', 'Artistic Gymnastics', '2024-08-01', 'Women''s All-Around Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Jumping Team', 'EQU', 'Equestrian', '2024-08-02', 'Jumping Team Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s High Jump', 'ATH', 'Athletics', '2024-08-02', 'Women''s High Jump Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 200m', 'ATH', 'Athletics', '2024-08-05', 'Men''s 200m Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 100m Breaststroke', 'SWM', 'Swimming', '2024-07-29', 'Women''s 100m Breaststroke Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Ã‰pÃ©e Individual', 'FEN', 'Fencing', '2024-07-27', 'Women''s Ã‰pÃ©e Individual Table of 64');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 92kg', 'BOX', 'Boxing', '2024-08-09', 'Men''s 92kg - Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -58kg', 'TKW', 'Taekwondo', '2024-08-07', 'Men -58kg Round of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Individual', 'MPN', 'Modern Pentathlon', '2024-08-08', 'Women''s Individual Ranking Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 800m Freestyle', 'SWM', 'Swimming', '2024-08-03', 'Women''s 800m Freestyle Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Singles', 'TEN', 'Tennis', '2024-07-30', 'Women''s Singles Third Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 100m Backstroke', 'SWM', 'Swimming', '2024-07-28', 'Men''s 100m Backstroke - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Kayak Cross', 'CSL', 'Canoe Slalom', '2024-08-05', 'Men''s Kayak Cross Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 400m', 'ATH', 'Athletics', '2024-08-04', 'Men''s 400m Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 200m Backstroke', 'SWM', 'Swimming', '2024-08-02', 'Women''s 200m Backstroke Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Jumping Individual', 'EQU', 'Equestrian', '2024-08-06', 'Jumping Individual Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Team', 'ARC', 'Archery', '2024-07-28', 'Women''s Team Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Discus Throw', 'ATH', 'Athletics', '2024-08-02', 'Women''s Discus Throw Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s High Jump', 'ATH', 'Athletics', '2024-08-10', 'Men''s High Jump Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -66 kg', 'JUD', 'Judo', '2024-07-28', 'Men -66 kg Elimination Round of 32');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('10m Air Pistol Women', 'SHO', 'Shooting', '2024-07-26', '10m Air Pistol Women Training');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Dinghy', 'SAL', 'Sailing', '2024-08-05', 'Women''s Dinghy Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Kayak Four 500m', 'CSP', 'Canoe Sprint', '2024-08-06', 'Men''s Kayak Four 500m Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 100m Freestyle', 'SWM', 'Swimming', '2024-07-30', 'Men''s 100m Freestyle Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 400m Individual Medley', 'SWM', 'Swimming', '2024-07-29', 'Women''s 400m Individual Medley - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Parallel Bars', 'GAR', 'Artistic Gymnastics', '2024-08-05', 'Men''s Parallel Bars Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 200m Individual Medley', 'SWM', 'Swimming', '2024-08-02', 'Women''s 200m Individual Medley - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Four', 'ROW', 'Rowing', '2024-07-28', 'Women''s Four Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 4 x 100m Freestyle Relay', 'SWM', 'Swimming', '2024-07-27', 'Men''s 4 x 100m Freestyle Relay Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('25m Pistol Women', 'SHO', 'Shooting', '2024-08-03', '25m Pistol Women''s Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'SRF', 'Surfing', '2024-07-29', 'Men''s Round 3');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Singles', 'TTE', 'Table Tennis', '2024-07-29', 'Women''s Singles Round of 64');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -80kg', 'TKW', 'Taekwondo', '2024-08-09', 'Men -80kg Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 50kg', 'BOX', 'Boxing', '2024-08-01', 'Women''s 50kg - Prelims - Round of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Foil Individual', 'FEN', 'Fencing', '2024-07-28', 'Women''s Foil Individual Table of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 100m Backstroke', 'SWM', 'Swimming', '2024-07-30', 'Women''s 100m Backstroke Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 1500m Freestyle', 'SWM', 'Swimming', '2024-07-31', 'Women''s 1500m Freestyle Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Kite', 'SAL', 'Sailing', '2024-08-07', 'Women''s Kite Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Sabre Team', 'FEN', 'Fencing', '2024-08-03', 'Women''s Sabre Team Classifications 5-8');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 1500m', 'ATH', 'Athletics', '2024-08-07', 'Women''s 1500m Repechage Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('10m Air Rifle Mixed Team', 'SHO', 'Shooting', '2024-07-27', '10m Air Rifle Mixed Team Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Road Race', 'CRD', 'Cycling Road', '2024-08-03', 'Men''s Road Race');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed Doubles', 'TEN', 'Tennis', '2024-07-29', 'Mixed Doubles First Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Individual Time Trial', 'CRD', 'Cycling Road', '2024-07-27', 'Men''s Individual Time Trial');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Freestyle 76kg', 'WRE', 'Wrestling', '2024-08-11', 'WFS 76kg Bronze Medal Matches');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Kayak Double 500m', 'CSP', 'Canoe Sprint', '2024-08-09', 'Men''s Kayak Double 500m Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -67kg', 'TKW', 'Taekwondo', '2024-08-09', 'Women -67kg Bronze Medal Contests');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Boulder & Lead', 'CLB', 'Sport Climbing', '2024-08-07', 'Men''s Boulder & Lead Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('10m Air Rifle Women', 'SHO', 'Shooting', '2024-07-27', '10m Air Rifle Women''s Training');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 800m', 'ATH', 'Athletics', '2024-08-09', 'Men''s 800m Semi-Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s +92kg', 'BOX', 'Boxing', '2024-08-10', 'Men''s +92kg - Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 4 x 100m Freestyle Relay', 'SWM', 'Swimming', '2024-07-27', 'Women''s 4 x 100m Freestyle Relay - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Park', 'BMF', 'Cycling BMX Freestyle', '2024-07-31', 'Men''s Park Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Ã‰pÃ©e Individual', 'FEN', 'Fencing', '2024-07-28', 'Men''s Ã‰pÃ©e Individual Table of 32');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Team', 'GAR', 'Artistic Gymnastics', '2024-07-30', 'Women''s Team Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Singles', 'TEN', 'Tennis', '2024-08-02', 'Men''s Singles Semi-finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 110m Hurdles', 'ATH', 'Athletics', '2024-08-04', 'Men''s 110m Hurdles Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed Team', 'ARC', 'Archery', '2024-08-02', 'Mixed Team Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Skiff', 'SAL', 'Sailing', '2024-07-29', 'Women''s Skiff Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Windsurfing', 'SAL', 'Sailing', '2024-08-01', 'Women''s Windsurfing Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Canoe Double 500m', 'CSP', 'Canoe Sprint', '2024-08-06', 'Women''s Canoe Double 500m Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Speed', 'CLB', 'Sport Climbing', '2024-08-07', 'Women''s Speed Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 400m', 'ATH', 'Athletics', '2024-08-05', 'Women''s 400m Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Hammer Throw', 'ATH', 'Athletics', '2024-08-04', 'Women''s Hammer Throw Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men', 'GTR', 'Trampoline Gymnastics', '2024-08-02', 'Men''s Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 200m Breaststroke', 'SWM', 'Swimming', '2024-07-30', 'Men''s 200m Breaststroke Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Synchronised 10m Platform', 'DIV', 'Diving', '2024-07-31', 'Women''s Synchronised 10m Platform');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Freestyle 57kg', 'WRE', 'Wrestling', '2024-08-09', 'WFS 57kg Repechage');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Skeet Men', 'SHO', 'Shooting', '2024-08-03', 'Skeet Men''s Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Quadruple Sculls', 'ROW', 'Rowing', '2024-07-29', 'Women''s Quad. Sculls Repechages');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed Dinghy', 'SAL', 'Sailing', '2024-08-06', 'Mixed Dinghy Opening Series');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 5000m', 'ATH', 'Athletics', '2024-08-05', 'Women''s 5000m Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('50m Rifle 3 Positions Women', 'SHO', 'Shooting', '2024-08-02', '50m Rifle 3 Positions Women''s Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 59kg', 'WLF', 'Weightlifting', '2024-08-08', 'Women''s 59kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Greco-Roman 77kg', 'WRE', 'Wrestling', '2024-08-07', 'MGR 77kg Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Greco-Roman 60kg', 'WRE', 'Wrestling', '2024-08-06', 'MGR 60kg Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Ã‰pÃ©e Team', 'FEN', 'Fencing', '2024-08-02', 'Men''s Ã‰pÃ©e Team Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Skeet Women', 'SHO', 'Shooting', '2024-08-03', 'Skeet Women''s Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -60 kg', 'JUD', 'Judo', '2024-07-27', 'Men -60 kg Elimination Round of 32');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s +102kg', 'WLF', 'Weightlifting', '2024-08-10', 'Men''s +102kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 57kg', 'BOX', 'Boxing', '2024-08-02', 'Women''s 57kg - Prelims - Round of 16');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men -68kg', 'TKW', 'Taekwondo', '2024-08-08', 'Men -68kg Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 57kg', 'BOX', 'Boxing', '2024-08-10', 'Men''s 57kg - Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 4 x 100m Relay', 'ATH', 'Athletics', '2024-08-09', 'Men''s 4 x 100m Relay Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Road Race', 'CRD', 'Cycling Road', '2024-08-04', 'Women''s Road Race');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Individual Time Trial', 'CRD', 'Cycling Road', '2024-07-27', 'Women''s Individual Time Trial');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Cross-country', 'MTB', 'Cycling Mountain Bike', '2024-07-28', 'Women''s Cross-country');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 400m Hurdles', 'ATH', 'Athletics', '2024-08-06', 'Men''s 400m Hurdles Repechage Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Pair', 'ROW', 'Rowing', '2024-07-31', 'Women''s Pair Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Horizontal Bar', 'GAR', 'Artistic Gymnastics', '2024-08-05', 'Men''s Horizontal Bar Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 50m Freestyle', 'SWM', 'Swimming', '2024-08-02', 'Men''s 50m Freestyle Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Eventing Team', 'EQU', 'Equestrian', '2024-07-28', 'Eventing Team Cross Country');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 200m Freestyle', 'SWM', 'Swimming', '2024-07-28', 'Men''s 200m Freestyle - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('10m Air Pistol Men', 'SHO', 'Shooting', '2024-07-27', '10m Air Pistol Men''s Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 20km Race Walk', 'ATH', 'Athletics', '2024-08-01', 'Men''s 20km Race Walk Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Kayak Four 500m', 'CSP', 'Canoe Sprint', '2024-08-06', 'Women''s Kayak Four 500m Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women -57kg', 'TKW', 'Taekwondo', '2024-08-08', 'Women -57kg Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 49kg', 'WLF', 'Weightlifting', '2024-08-07', 'Women''s 49kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Floor Exercise', 'GAR', 'Artistic Gymnastics', '2024-08-05', 'Women''s Floor Exercise Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Freestyle 50kg', 'WRE', 'Wrestling', '2024-08-07', 'WFS 50kg Bronze Medal Matches');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 10,000m', 'ATH', 'Athletics', '2024-08-09', 'Women''s 10,000m Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('50m Rifle 3 Positions Men', 'SHO', 'Shooting', '2024-07-31', '50m Rifle 3 Pos. Men''s Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Canoe Single 1000m', 'CSP', 'Canoe Sprint', '2024-08-09', 'Men''s Canoe Single 1000m Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Dressage Individual', 'EQU', 'Equestrian', '2024-07-31', 'Dressage Individual Grand Prix');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Group All-Around', 'GRY', 'Rhythmic Gymnastics', '2024-08-09', 'Group All-Around Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Park', 'SKB', 'Skateboarding', '2024-08-07', 'Men''s Park Prelims');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 4 x 200m Freestyle Relay', 'SWM', 'Swimming', '2024-07-30', 'Men''s 4 x 200m Freestyle Relay - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Kayak Cross', 'CSL', 'Canoe Slalom', '2024-08-02', 'Women''s Kayak Cross Time Trial');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Synchronised 3m Springboard', 'DIV', 'Diving', '2024-07-27', 'Women''s Synchronised 3m Springboard');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Trap Women', 'SHO', 'Shooting', '2024-07-30', 'Trap Women''s Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('25m Rapid Fire Pistol Men', 'SHO', 'Shooting', '2024-08-03', '25m Rapid Fire Pistol Men''s Training');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 60kg', 'BOX', 'Boxing', '2024-07-31', 'Women''s 60kg - Quarterfinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 10km', 'OWS', 'Marathon Swimming', '2024-08-08', 'Women''s 10km');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Javelin Throw', 'ATH', 'Athletics', '2024-08-06', 'Men''s Javelin Throw Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s +81kg', 'WLF', 'Weightlifting', '2024-08-11', 'Women''s +81kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Shot Put', 'ATH', 'Athletics', '2024-08-08', 'Women''s Shot Put Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Keirin', 'CTR', 'Cycling Track', '2024-08-11', 'Men''s Keirin, Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Duet', 'SWA', 'Artistic Swimming', '2024-08-09', 'Duet Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 200m Butterfly', 'SWM', 'Swimming', '2024-07-30', 'Men''s 200m Butterfly - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Heptathlon', 'ATH', 'Athletics', '2024-08-08', 'Women''s Heptathlon 100m Hurdles');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Pair', 'ROW', 'Rowing', '2024-07-28', 'Men''s Pair Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Eight', 'ROW', 'Rowing', '2024-08-01', 'Men''s Eight Repechages');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 200m Individual Medley', 'SWM', 'Swimming', '2024-08-01', 'Men''s 200m Individual Medley Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 400m Hurdles', 'ATH', 'Athletics', '2024-08-04', 'Women''s 400m Hurdles Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Sabre Team', 'FEN', 'Fencing', '2024-07-31', 'Men''s Sabre Team Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 3m Springboard', 'DIV', 'Diving', '2024-08-06', 'Men''s 3m Springboard Preliminary');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Mixed 4 x 100m Medley Relay', 'SWM', 'Swimming', '2024-08-02', 'Mixed 4 x 100m Medley Relay - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Freestyle 125kg', 'WRE', 'Wrestling', '2024-08-09', 'MFS 125kg Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Kayak Single 1000m', 'CSP', 'Canoe Sprint', '2024-08-07', 'Men''s Kayak Single 1000m Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Park', 'SKB', 'Skateboarding', '2024-08-06', 'Women''s Park Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 400m Freestyle', 'SWM', 'Swimming', '2024-07-27', 'Men''s 400m Freestyle - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Madison', 'CTR', 'Cycling Track', '2024-08-09', 'Women''s Madison, Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women', 'GTR', 'Trampoline Gymnastics', '2024-08-02', 'Women''s Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Kayak Single', 'CSL', 'Canoe Slalom', '2024-08-01', 'Men''s Kayak Single Semifinal');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 3000m Steeplechase', 'ATH', 'Athletics', '2024-08-05', 'Men''s 3000m Steeplechase Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Double Sculls', 'ROW', 'Rowing', '2024-07-28', 'Women''s Double Sculls Repechages');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 800m', 'ATH', 'Athletics', '2024-08-02', 'Women''s 800m Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 10km', 'OWS', 'Marathon Swimming', '2024-08-09', 'Men''s 10km');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Canoe Single', 'CSL', 'Canoe Slalom', '2024-07-29', 'Men''s Canoe Single Semifinal');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Shot Put', 'ATH', 'Athletics', '2024-08-03', 'Men''s Shot Put Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Uneven Bars', 'GAR', 'Artistic Gymnastics', '2024-08-04', 'Women''s Uneven Bars Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Park', 'BMF', 'Cycling BMX Freestyle', '2024-07-30', 'Women''s Park Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Synchronised 3m Springboard', 'DIV', 'Diving', '2024-08-02', 'Men''s Synchronised 3m Springboard');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 400m Individual Medley', 'SWM', 'Swimming', '2024-07-28', 'Men''s 400m Individual Medley - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 4 x 400m Relay', 'ATH', 'Athletics', '2024-08-10', 'Men''s 4 x 400m Relay Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Pole Vault', 'ATH', 'Athletics', '2024-08-03', 'Men''s Pole Vault Qualification');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 10m Platform', 'DIV', 'Diving', '2024-08-09', 'Men''s 10m Platform Preliminary');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 100m Butterfly', 'SWM', 'Swimming', '2024-07-28', 'Women''s 100m Butterfly Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Vault', 'GAR', 'Artistic Gymnastics', '2024-08-04', 'Men''s Vault Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Team Pursuit', 'CTR', 'Cycling Track', '2024-08-07', 'Women''s Team Pursuit, Finals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 20km Race Walk', 'ATH', 'Athletics', '2024-08-01', 'Women''s 20km Race Walk Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Kayak Double 500m', 'CSP', 'Canoe Sprint', '2024-08-09', 'Women''s Kayak Double 500m Semifinals');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 4 x 100m Relay', 'ATH', 'Athletics', '2024-08-08', 'Women''s 4 x 100m Relay Round 1');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 102kg', 'WLF', 'Weightlifting', '2024-08-10', 'Men''s 102kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 200m Backstroke', 'SWM', 'Swimming', '2024-07-31', 'Men''s 200m Backstroke - Heats');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Cross-country', 'MTB', 'Cycling Mountain Bike', '2024-07-29', 'Men''s Cross-country');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Triple Jump', 'ATH', 'Athletics', '2024-08-03', 'Women''s Triple Jump Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 73kg', 'WLF', 'Weightlifting', '2024-08-08', 'Men''s 73kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Team Pursuit', 'CTR', 'Cycling Track', '2024-08-06', 'Men''s Team Pursuit, First Round');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 81kg', 'WLF', 'Weightlifting', '2024-08-10', 'Women''s 81kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 4 x 400m Relay', 'ATH', 'Athletics', '2024-08-10', 'Women''s 4 x 400m Relay Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Balance Beam', 'GAR', 'Artistic Gymnastics', '2024-08-05', 'Women''s Balance Beam Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Javelin Throw', 'ATH', 'Athletics', '2024-08-10', 'Women''s Javelin Throw Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Long Jump', 'ATH', 'Athletics', '2024-08-06', 'Men''s Long Jump Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Pole Vault', 'ATH', 'Athletics', '2024-08-07', 'Women''s Pole Vault Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 61kg', 'WLF', 'Weightlifting', '2024-08-07', 'Men''s 61kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 3000m Steeplechase', 'ATH', 'Athletics', '2024-08-06', 'Women''s 3000m Steeplechase Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Vault', 'GAR', 'Artistic Gymnastics', '2024-08-03', 'Women''s Vault Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Triple Jump', 'ATH', 'Athletics', '2024-08-09', 'Men''s Triple Jump Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Pommel Horse', 'GAR', 'Artistic Gymnastics', '2024-08-03', 'Men''s Pommel Horse Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s 71kg', 'WLF', 'Weightlifting', '2024-08-09', 'Women''s 71kg');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Street', 'SKB', 'Skateboarding', '2024-07-29', 'Men''s Street Prelims');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Marathon', 'ATH', 'Athletics', '2024-08-11', 'Women''s Marathon Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('4 x 400m Relay Mixed', 'ATH', 'Athletics', '2024-08-03', '4 x 400m Relay Mixed Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Women''s Individual', 'TRI', 'Triathlon', '2024-07-31', 'Women''s Individual');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Synchronised 10m Platform', 'DIV', 'Diving', '2024-07-29', 'Men''s Synchronised 10m Platform');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s 10,000m', 'ATH', 'Athletics', '2024-08-02', 'Men''s 10,000m Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Team', 'GAR', 'Artistic Gymnastics', '2024-07-29', 'Men''s Team Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Marathon', 'ATH', 'Athletics', '2024-08-10', 'Men''s Marathon Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s All-Around', 'GAR', 'Artistic Gymnastics', '2024-07-31', 'Men''s All-Around Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Floor Exercise', 'GAR', 'Artistic Gymnastics', '2024-08-03', 'Men''s Floor Exercise Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Hammer Throw', 'ATH', 'Athletics', '2024-08-04', 'Men''s Hammer Throw Final');
INSERT INTO Event (Event_Name, Sport_Code, Sport_Type, Day, Phase) VALUES ('Men''s Madison', 'CTR', 'Cycling Track', '2024-08-10', 'Men''s Madison, Final');
