USE Olympics_21936856;


INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (1, 'CSPMC2-500M-ANG01', 'ANTONIO Manuel / SANDA Benilson', 'Canoe Sprint', 'Mens Canoe Double 500m', 1896956, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (2, 'CSPMC2-500M-ANG01', 'ANTONIO Manuel / SANDA Benilson', 'Canoe Sprint', 'Mens Canoe Double 500m', 1896963, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (3, 'ROWMSCULL2-LARG01', 'Argentina', 'Rowing', 'Lightweight Mens Double Sculls', 1892874, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (4, 'ROWMSCULL2-LARG01', 'Argentina', 'Rowing', 'Lightweight Mens Double Sculls', 1892944, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (5, 'ROWWSCULL2-LARG01', 'Argentina', 'Rowing', 'Lightweight Womens Double Sculls', 1892797, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (6, 'ROWWSCULL2-LARG01', 'Argentina', 'Rowing', 'Lightweight Womens Double Sculls', 1893011, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (7, 'CTRMMADISON-AUT01', 'Austria', 'Cycling Track', 'Mens Madison', 1566120, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (8, 'CTRMMADISON-AUT01', 'Austria', 'Cycling Track', 'Mens Madison', 1566122, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (9, 'EQUODRESTEAMAUT01', 'Austria', 'Equestrian', 'Dressage Team', 1878961, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (10, 'EQUODRESTEAMAUT01', 'Austria', 'Equestrian', 'Dressage Team', 1878962, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (11, 'EQUODRESTEAMAUT01', 'Austria', 'Equestrian', 'Dressage Team', 1878963, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (12, 'EQUODRESTEAMAUT01', 'Austria', 'Equestrian', 'Dressage Team', 1878965, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (13, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903237, 1903896);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (14, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1915389, 1903899);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (15, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903240, 1922671);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (16, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903209, 1942806);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (17, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903206, 1949449);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (18, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903212, 1949459);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (19, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903222, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (20, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903214, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (21, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1915391, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (22, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903213, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (23, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903224, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (24, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903226, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (25, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903242, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (26, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1915386, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (27, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1915390, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (28, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1903229, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (29, 'HOCMTEAM11--BEL01', 'Belgium', 'Hockey', 'Men', 1915388, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (30, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903233, 1903894);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (31, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903227, 1903897);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (32, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903234, 1903898);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (33, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1915387, 1922670);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (34, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1915394, 1922672);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (35, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903232, 1922673);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (36, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903243, 1942804);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (37, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903219, 1942833);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (38, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903205, 1942834);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (39, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903238, 1949449);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (40, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903228, 1963552);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (41, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1915392, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (42, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903223, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (43, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903230, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (44, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903202, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (45, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903208, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (46, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903207, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (47, 'HOCWTEAM11--BEL01', 'Belgium', 'Hockey', 'Women', 1903203, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (48, 'ARCXTEAM2---BRA01', 'Brazil', 'Archery', 'Mixed Team', 1958706, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (49, 'ARCXTEAM2---BRA01', 'Brazil', 'Archery', 'Mixed Team', 1958717, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (50, 'SALM49ER----BRA01', 'SOFFIATTI GRAEL Marco / SIMOES Gabriel', 'Sailing', 'Mens Skiff', 1961066, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (51, 'SALM49ER----BRA01', 'SOFFIATTI GRAEL Marco / SIMOES Gabriel', 'Sailing', 'Mens Skiff', 1961057, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (52, 'SALW49ERFX--BRA01', 'SOFFIATTI GRAEL Martine / KUNZE Kahena', 'Sailing', 'Womens Skiff', 1961065, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (53, 'SALW49ERFX--BRA01', 'SOFFIATTI GRAEL Martine / KUNZE Kahena', 'Sailing', 'Womens Skiff', 1961062, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (54, 'SALX470-----BRA01', 'DUARTE HADDAD Henrique / SWAN Isabel', 'Sailing', 'Mixed Dinghy', 1961058, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (55, 'SALX470-----BRA01', 'DUARTE HADDAD Henrique / SWAN Isabel', 'Sailing', 'Mixed Dinghy', 1961059, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (56, 'SALXNACRA17-BRA01', 'SIEMSEN Joao / ARNDT Marina', 'Sailing', 'Mixed Multihull', 1961061, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (57, 'SALXNACRA17-BRA01', 'SIEMSEN Joao / ARNDT Marina', 'Sailing', 'Mixed Multihull', 1961064, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (58, 'TENMDOUBLES-BRA01', 'Monteiro / Seyboth Wild', 'Tennis', 'Mens Doubles', 1955869, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (59, 'TENMDOUBLES-BRA01', 'Monteiro / Seyboth Wild', 'Tennis', 'Mens Doubles', 1955871, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (60, 'TENWDOUBLES-BRA01', 'Haddad Maia / Stefani', 'Tennis', 'Womens Doubles', 1955853, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (61, 'TENWDOUBLES-BRA01', 'Haddad Maia / Stefani', 'Tennis', 'Womens Doubles', 1955862, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (62, 'TENXDOUBLES-BRA01', 'Stefani / Seyboth Wild', 'Tennis', 'Mixed Doubles', 1955862, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (63, 'TENXDOUBLES-BRA01', 'Stefani / Seyboth Wild', 'Tennis', 'Mixed Doubles', 1955871, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (64, 'CSPWC2-500M-CAN01', 'MACKENZIE Sloan / VINCENT Katie', 'Canoe Sprint', 'Womens Canoe Double 500m', 1964583, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (65, 'CSPWC2-500M-CAN01', 'MACKENZIE Sloan / VINCENT Katie', 'Canoe Sprint', 'Womens Canoe Double 500m', 1964547, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (66, 'CSPWK2-500M-CAN01', 'STOTT Courtney / DAVISON Natalie', 'Canoe Sprint', 'Womens Kayak Double 500m', 1964567, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (67, 'CSPWK2-500M-CAN01', 'STOTT Courtney / DAVISON Natalie', 'Canoe Sprint', 'Womens Kayak Double 500m', 1964579, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (68, 'CTRMMADISON-CAN01', 'Canada', 'Cycling Track', 'Mens Madison', 1966690, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (69, 'CTRMMADISON-CAN01', 'Canada', 'Cycling Track', 'Mens Madison', 1966691, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (70, 'CTRWMADISON-CAN01', 'Canada', 'Cycling Track', 'Womens Madison', 1966652, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (71, 'CTRWMADISON-CAN01', 'Canada', 'Cycling Track', 'Womens Madison', 1966688, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (72, 'ATHX42KWALKTCHN01', 'ZHANG Jun / YANG Jiayu', 'Athletics', 'Marathon Race Walk Relay Mixed', 1918996, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (73, 'ATHX42KWALKTCHN01', 'ZHANG Jun / YANG Jiayu', 'Athletics', 'Marathon Race Walk Relay Mixed', 1919002, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (74, 'ATHX42KWALKTCHN02', 'HE X / QIEYANG S', 'Athletics', 'Marathon Race Walk Relay Mixed', 1918995, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (75, 'ATHX42KWALKTCHN02', 'HE X / QIEYANG S', 'Athletics', 'Marathon Race Walk Relay Mixed', 1919008, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (76, 'BDMMDOUBLES-CHN01', 'LIU Yu Chen / OU Xuan Yi', 'Badminton', 'Mens Doubles', 1913425, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (77, 'BDMMDOUBLES-CHN01', 'LIU Yu Chen / OU Xuan Yi', 'Badminton', 'Mens Doubles', 1913426, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (78, 'BDMMDOUBLES-CHN02', 'LIANG Wei Keng / WANG Chang', 'Badminton', 'Mens Doubles', 1913424, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (79, 'BDMMDOUBLES-CHN02', 'LIANG Wei Keng / WANG Chang', 'Badminton', 'Mens Doubles', 1913429, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (80, 'BDMWDOUBLES-CHN01', 'LIU Sheng Shu / TAN Ning', 'Badminton', 'Womens Doubles', 1913441, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (81, 'BDMWDOUBLES-CHN01', 'LIU Sheng Shu / TAN Ning', 'Badminton', 'Womens Doubles', 1913442, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (82, 'BDMWDOUBLES-CHN02', 'CHEN Qing Chen / JIA Yi Fan', 'Badminton', 'Womens Doubles', 1913438, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (83, 'BDMWDOUBLES-CHN02', 'CHEN Qing Chen / JIA Yi Fan', 'Badminton', 'Womens Doubles', 1913439, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (84, 'ATHX42KWALKTCOL01', 'ROMERO M / ARENAS L', 'Athletics', 'Marathon Race Walk Relay Mixed', 1965718, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (85, 'ATHX42KWALKTCOL01', 'ROMERO M / ARENAS L', 'Athletics', 'Marathon Race Walk Relay Mixed', 1532951, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (86, 'ATHX42KWALKTCOL02', 'HERRERA/MOJICA CHALARCA', 'Athletics', 'Marathon Race Walk Relay Mixed', 1543481, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (87, 'ATHX42KWALKTCOL02', 'HERRERA/MOJICA CHALARCA', 'Athletics', 'Marathon Race Walk Relay Mixed', 1917388, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (88, 'ROWMNOCOX2--CRO01', 'Croatia', 'Rowing', 'Mens Pair', 1916685, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (89, 'ROWMNOCOX2--CRO01', 'Croatia', 'Rowing', 'Mens Pair', 1921490, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (90, 'CSPWC2-500M-CUB01', 'CIRILO DUBOYS Yarisleidis / LOPEZ LAMADRID Yinnoly Francheska', 'Canoe Sprint', 'Womens Canoe Double 500m', 1564506, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (91, 'CSPWC2-500M-CUB01', 'CIRILO DUBOYS Yarisleidis / LOPEZ LAMADRID Yinnoly Francheska', 'Canoe Sprint', 'Womens Canoe Double 500m', 1564508, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (92, 'ARCXTEAM2---CZE01', 'Czechia', 'Archery', 'Mixed Team', 1894503, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (93, 'ARCXTEAM2---CZE01', 'Czechia', 'Archery', 'Mixed Team', 1894507, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (94, 'ATHX42KWALKTCZE01', 'HLAVAC V / MARTINKOVA E', 'Athletics', 'Marathon Race Walk Relay Mixed', 1892108, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (95, 'ATHX42KWALKTCZE01', 'HLAVAC V / MARTINKOVA E', 'Athletics', 'Marathon Race Walk Relay Mixed', 1892131, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (96, 'BDMMDOUBLES-DEN01', 'ASTRUP Kim / RASMUSSEN Anders Skaarup', 'Badminton', 'Mens Doubles', 1888998, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (97, 'BDMMDOUBLES-DEN01', 'ASTRUP Kim / RASMUSSEN Anders Skaarup', 'Badminton', 'Mens Doubles', 1888999, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (98, 'GRYW5AA-----EGY01', 'Egypt', 'Rhythmic Gymnastics', 'Group All-Around', 1562782, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (99, 'GRYW5AA-----EGY01', 'Egypt', 'Rhythmic Gymnastics', 'Group All-Around', 1562596, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (100, 'GRYW5AA-----EGY01', 'Egypt', 'Rhythmic Gymnastics', 'Group All-Around', 1562222, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (101, 'GRYW5AA-----EGY01', 'Egypt', 'Rhythmic Gymnastics', 'Group All-Around', 1978541, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (102, 'GRYW5AA-----EGY01', 'Egypt', 'Rhythmic Gymnastics', 'Group All-Around', 1978514, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (103, 'SWAWTEAM2---EGY01', 'Egypt', 'Artistic Swimming', 'Duet', 1888980, 1903722);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (104, 'SWAWTEAM2---EGY01', 'Egypt', 'Artistic Swimming', 'Duet', 1888861, 1903754);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (105, 'ARCXTEAM2---FRA01', 'France', 'Archery', 'Mixed Team', 1541265, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (106, 'ARCXTEAM2---FRA01', 'France', 'Archery', 'Mixed Team', 1541270, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (107, 'ATHM4X100M--FRA01', 'France', 'Athletics', 'Mens 4 x 100m Relay', 1910609, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (108, 'ATHM4X100M--FRA01', 'France', 'Athletics', 'Mens 4 x 100m Relay', 1910733, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (109, 'ATHM4X100M--FRA01', 'France', 'Athletics', 'Mens 4 x 100m Relay', 1911843, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (110, 'ATHM4X100M--FRA01', 'France', 'Athletics', 'Mens 4 x 100m Relay', 1911898, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (111, 'ATHM4X100M--FRA01', 'France', 'Athletics', 'Mens 4 x 100m Relay', 1911975, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (112, 'ATHM4X100M--FRA01', 'France', 'Athletics', 'Mens 4 x 100m Relay', 1911988, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (113, 'ATHM4X100M--FRA01', 'France', 'Athletics', 'Mens 4 x 100m Relay', 1911990, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (114, 'FENMTEAMFOILFRA01', 'France', 'Fencing', 'Mens Foil Team', 1916213, 1916244);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (115, 'FENMTEAMFOILFRA01', 'France', 'Fencing', 'Mens Foil Team', 1916215, 1916263);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (116, 'FENMTEAMFOILFRA01', 'France', 'Fencing', 'Mens Foil Team', 1916216, 1916264);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (117, 'FENMTEAMFOILFRA01', 'France', 'Fencing', 'Mens Foil Team', 1916217, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (118, 'FENMTEAMSABRFRA01', 'France', 'Fencing', 'Mens Sabre Team', 1916230, 1916242);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (119, 'FENMTEAMSABRFRA01', 'France', 'Fencing', 'Mens Sabre Team', 1916231, 1916244);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (120, 'FENMTEAMSABRFRA01', 'France', 'Fencing', 'Mens Sabre Team', 1916232, 1916268);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (121, 'FENMTEAMSABRFRA01', 'France', 'Fencing', 'Mens Sabre Team', 1916234, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (122, 'DIVM10MTEAM2GER01', 'Germany', 'Diving', 'Mens Synchronised 10m Platform', 1907200, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (123, 'DIVM10MTEAM2GER01', 'Germany', 'Diving', 'Mens Synchronised 10m Platform', 1907214, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (124, 'DIVW3MTEAM2-GER01', 'Germany', 'Diving', 'Womens Synchronised 3m Springboard', 1907201, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (125, 'DIVW3MTEAM2-GER01', 'Germany', 'Diving', 'Womens Synchronised 3m Springboard', 1907203, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (126, 'ROWMSCULL4--GER01', 'Germany', 'Rowing', 'Mens Quadruple Sculls', 1906480, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (127, 'ROWMSCULL4--GER01', 'Germany', 'Rowing', 'Mens Quadruple Sculls', 1906477, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (128, 'ROWMSCULL4--GER01', 'Germany', 'Rowing', 'Mens Quadruple Sculls', 1906496, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (129, 'ROWMSCULL4--GER01', 'Germany', 'Rowing', 'Mens Quadruple Sculls', 1906514, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (130, 'SALM49ER----GER01', 'MEGGENDORFER Jakob / SPRANGER Andreas', 'Sailing', 'Mens Skiff', 1891964, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (131, 'SALM49ER----GER01', 'MEGGENDORFER Jakob / SPRANGER Andreas', 'Sailing', 'Mens Skiff', 1891965, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (132, 'SALW49ERFX--GER01', 'BERGMANN Marla / WILLE Hanna', 'Sailing', 'Womens Skiff', 1891987, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (133, 'SALW49ERFX--GER01', 'BERGMANN Marla / WILLE Hanna', 'Sailing', 'Womens Skiff', 1891988, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (134, 'SALX470-----GER01', 'DIESCH Simon / MARKFORT Anna', 'Sailing', 'Mixed Dinghy', 1891960, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (135, 'SALX470-----GER01', 'DIESCH Simon / MARKFORT Anna', 'Sailing', 'Mixed Dinghy', 1891963, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (136, 'SALXNACRA17-GER01', 'KOHLHOFF Paul / STUHLEMMER Alica', 'Sailing', 'Mixed Multihull', 1891956, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (137, 'SALXNACRA17-GER01', 'KOHLHOFF Paul / STUHLEMMER Alica', 'Sailing', 'Mixed Multihull', 1891970, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (138, 'ARCMTEAM3---GBR01', 'Great Britain', 'Archery', 'Mens Team', 1560988, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (139, 'ARCMTEAM3---GBR01', 'Great Britain', 'Archery', 'Mens Team', 1560989, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (140, 'ARCMTEAM3---GBR01', 'Great Britain', 'Archery', 'Mens Team', 1561003, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (141, 'ARCWTEAM3---GBR01', 'Great Britain', 'Archery', 'Womens Team', 1560991, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (142, 'ARCWTEAM3---GBR01', 'Great Britain', 'Archery', 'Womens Team', 1560990, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (143, 'ARCWTEAM3---GBR01', 'Great Britain', 'Archery', 'Womens Team', 1561000, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (144, 'TENWDOUBLES-GRE01', 'Papamichail / Sakkari', 'Tennis', 'Womens Doubles', 4979624, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (145, 'TENWDOUBLES-GRE01', 'Papamichail / Sakkari', 'Tennis', 'Womens Doubles', 1961362, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (146, 'TENXDOUBLES-GRE01', 'Sakkari / Tsitsipas', 'Tennis', 'Mixed Doubles', 1961362, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (147, 'TENXDOUBLES-GRE01', 'Sakkari / Tsitsipas', 'Tennis', 'Mixed Doubles', 1961363, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (148, 'ATHX42KWALKTHUN01', 'VENYERCSAN B / RECSEI R', 'Athletics', 'Marathon Race Walk Relay Mixed', 1928799, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (149, 'ATHX42KWALKTHUN01', 'VENYERCSAN B / RECSEI R', 'Athletics', 'Marathon Race Walk Relay Mixed', 1927675, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (150, 'ARCXTEAM2---IND01', 'India', 'Archery', 'Mixed Team', 1546200, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (151, 'ARCXTEAM2---IND01', 'India', 'Archery', 'Mixed Team', 1546108, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (152, 'SHOXAPMT----IND01', 'India 1', 'Shooting', '10m Air Pistol Mixed Team', 1538159, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (153, 'SHOXAPMT----IND01', 'India 1', 'Shooting', '10m Air Pistol Mixed Team', 1545464, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (154, 'BDMMDOUBLES-INA01', 'ALFIAN Fajar / ARDIANTO Muhammad Rian', 'Badminton', 'Mens Doubles', 1926309, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (155, 'BDMMDOUBLES-INA01', 'ALFIAN Fajar / ARDIANTO Muhammad Rian', 'Badminton', 'Mens Doubles', 1926326, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (156, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892778, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (157, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892775, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (158, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892698, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (159, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892792, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (160, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892780, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (161, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892796, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (162, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892794, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (163, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892943, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (164, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892939, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (165, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892798, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (166, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892945, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (167, 'JUDXTEAM6---ISR01', 'Israel', 'Judo', 'Mixed Team', 1892957, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (168, 'VBVMTEAM2---ITA01', 'Cottafava/Nicolai', 'Beach Volleyball', 'Men', 1921949, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (169, 'VBVMTEAM2---ITA01', 'Cottafava/Nicolai', 'Beach Volleyball', 'Men', 1921948, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (170, 'BDMMDOUBLES-JPN01', 'HOKI Takuro / KOBAYASHI Yugo', 'Badminton', 'Mens Doubles', 1541623, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (171, 'BDMMDOUBLES-JPN01', 'HOKI Takuro / KOBAYASHI Yugo', 'Badminton', 'Mens Doubles', 1541624, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (172, 'ARCXTEAM2---KOR01', 'Republic of Korea', 'Archery', 'Mixed Team', 1902147, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (173, 'ARCXTEAM2---KOR01', 'Republic of Korea', 'Archery', 'Mixed Team', 1902135, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (174, 'BDMMDOUBLES-KOR01', 'KANG Min Hyuk / SEO Seung Jae', 'Badminton', 'Mens Doubles', 1891503, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (175, 'BDMMDOUBLES-KOR01', 'KANG Min Hyuk / SEO Seung Jae', 'Badminton', 'Mens Doubles', 1891511, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (176, 'BDMWDOUBLES-KOR01', 'BAEK Ha Na / LEE So Hee', 'Badminton', 'Womens Doubles', 1891499, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (177, 'BDMWDOUBLES-KOR01', 'BAEK Ha Na / LEE So Hee', 'Badminton', 'Womens Doubles', 1891510, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (178, 'SHOXAPMT----KOR02', 'Republic of Korea 2', 'Shooting', '10m Air Pistol Mixed Team', 1893930, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (179, 'SHOXAPMT----KOR02', 'Republic of Korea 2', 'Shooting', '10m Air Pistol Mixed Team', 1893852, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (180, 'CSPMK2-500M-LTU01', 'MALDONIS Mindaugas / OLIJNIK Andrej', 'Canoe Sprint', 'Mens Kayak Double 500m', 1888808, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (181, 'CSPMK2-500M-LTU01', 'MALDONIS Mindaugas / OLIJNIK Andrej', 'Canoe Sprint', 'Mens Kayak Double 500m', 1888820, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (182, 'TRIXTEAM4---MEX01', 'Mexico', 'Triathlon', 'Mixed Relay', 1535442, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (183, 'TRIXTEAM4---MEX01', 'Mexico', 'Triathlon', 'Mixed Relay', 1533189, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (184, 'TRIXTEAM4---MEX01', 'Mexico', 'Triathlon', 'Mixed Relay', 1533190, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (185, 'TRIXTEAM4---MEX01', 'Mexico', 'Triathlon', 'Mixed Relay', 1533188, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (186, 'BK3MTEAM3---NED01', 'Netherlands', '3x3 Basketball', 'Men', 1970800, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (187, 'BK3MTEAM3---NED01', 'Netherlands', '3x3 Basketball', 'Men', 1970792, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (188, 'BK3MTEAM3---NED01', 'Netherlands', '3x3 Basketball', 'Men', 1970796, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (189, 'BK3MTEAM3---NED01', 'Netherlands', '3x3 Basketball', 'Men', 1970797, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (190, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971941, 1972025);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (191, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971905, 1972034);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (192, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971929, 1972035);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (193, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971922, 1972045);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (194, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971917, 1972053);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (195, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971904, 1972055);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (196, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971921, 1972056);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (197, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971911, 1972126);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (198, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971976, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (199, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971980, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (200, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971934, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (201, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971909, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (202, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971956, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (203, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971932, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (204, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971910, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (205, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971963, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (206, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971968, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (207, 'HOCMTEAM11--NED01', 'Netherlands', 'Hockey', 'Men', 1971952, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (208, 'SALM49ER----NZL01', 'McHARDIE Isaac / McKENZIE William', 'Sailing', 'Mens Skiff', 1918833, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (209, 'SALM49ER----NZL01', 'McHARDIE Isaac / McKENZIE William', 'Sailing', 'Mens Skiff', 1918834, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (210, 'EQUOJUMPTEAMKSA01', 'Saudi Arabia', 'Equestrian', 'Jumping Team', 1898161, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (211, 'EQUOJUMPTEAMKSA01', 'Saudi Arabia', 'Equestrian', 'Jumping Team', 1898209, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (212, 'EQUOJUMPTEAMKSA01', 'Saudi Arabia', 'Equestrian', 'Jumping Team', 1898219, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (213, 'ATHX42KWALKTESP02', 'MARTIN A / PEREZ M', 'Athletics', 'Marathon Race Walk Relay Mixed', 1904165, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (214, 'ATHX42KWALKTESP02', 'MARTIN A / PEREZ M', 'Athletics', 'Marathon Race Walk Relay Mixed', 1905369, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (215, 'CSPMC2-500M-ESP01', 'MORENO Joan Antoni / DOMINGUEZ Diego', 'Canoe Sprint', 'Mens Canoe Double 500m', 1954023, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (216, 'CSPMC2-500M-ESP01', 'MORENO Joan Antoni / DOMINGUEZ Diego', 'Canoe Sprint', 'Mens Canoe Double 500m', 1953996, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (217, 'EQUODRESTEAMESP01', 'Spain', 'Equestrian', 'Dressage Team', 1965390, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (218, 'EQUODRESTEAMESP01', 'Spain', 'Equestrian', 'Dressage Team', 1965411, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (219, 'EQUODRESTEAMESP01', 'Spain', 'Equestrian', 'Dressage Team', 1965391, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (220, 'SALX470-----SWE01', 'DAHLBERG Anton / KARLSSON Lovisa', 'Sailing', 'Mixed Dinghy', 1564652, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (221, 'SALX470-----SWE01', 'DAHLBERG Anton / KARLSSON Lovisa', 'Sailing', 'Mixed Dinghy', 1564651, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (222, 'BDMMDOUBLES-THA01', 'JOMKOH Supak / KEDREN Kittinupong', 'Badminton', 'Mens Doubles', 1926300, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (223, 'BDMMDOUBLES-THA01', 'JOMKOH Supak / KEDREN Kittinupong', 'Badminton', 'Mens Doubles', 1926303, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (224, 'TENMDOUBLES-USA01', 'Fritz / Paul', 'Tennis', 'Mens Doubles', 1930782, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (225, 'TENMDOUBLES-USA01', 'Fritz / Paul', 'Tennis', 'Mens Doubles', 1930801, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (226, 'TENMDOUBLES-USA02', 'Krajicek / Ram', 'Tennis', 'Mens Doubles', 1930790, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (227, 'TENMDOUBLES-USA02', 'Krajicek / Ram', 'Tennis', 'Mens Doubles', 1930804, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (228, 'TENWDOUBLES-USA01', 'Gauff / Pegula', 'Tennis', 'Womens Doubles', 1930784, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (229, 'TENWDOUBLES-USA01', 'Gauff / Pegula', 'Tennis', 'Womens Doubles', 1930802, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (230, 'TENWDOUBLES-USA02', 'Collins / Krawczyk', 'Tennis', 'Womens Doubles', 1930776, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (231, 'TENWDOUBLES-USA03', 'Collins / Krawczyk', 'Tennis', 'Womens Doubles', 1930791, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (232, 'TENXDOUBLES-USA01', 'Gauff / Fritz', 'Tennis', 'Mixed Doubles', 1930784, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (233, 'TENXDOUBLES-USA01', 'Gauff / Fritz', 'Tennis', 'Mixed Doubles', 1930782, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (234, 'TRIXTEAM4---USA01', 'United States of America', 'Triathlon', 'Mixed Relay', 1930750, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (235, 'TRIXTEAM4---USA01', 'United States of America', 'Triathlon', 'Mixed Relay', 1930752, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (236, 'TRIXTEAM4---USA01', 'United States of America', 'Triathlon', 'Mixed Relay', 1930747, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (237, 'SALM49ER----URU01', 'UMPIERRE Hernan / DIZ Fernando', 'Sailing', 'Mens Skiff', 1922425, NULL);
INSERT INTO Team (Increment_ID, Team_Code, Team_Name, Discipline, Event, Athlete_Code, Coach_Code) VALUES (238, 'SALM49ER----URU01', 'UMPIERRE Hernan / DIZ Fernando', 'Sailing', 'Mens Skiff', 1922387, NULL);