USE Olympics_21936856;

INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1533246', 'PEDRERO Ofelia', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1535775', 'RADHI SHENAISHIL', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1536328', 'LOFTUS Adriana', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1538315', 'GULLA Alejandra', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1540522', 'MILANO Guillermo', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1540638', 'GOMEZ CORA Santiago', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1540639', 'GRAVANO Leonardo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1544157', 'THORPE Karen', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1544158', 'TOMOMATSU Yumiko', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1544489', 'CURRAN Orlaith', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1550038', 'ARILL Samuel', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1550039', 'MORALES OTERO Carlos', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1550047', 'BATISTA Gerardo', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1555115', 'FLANNERY Eimear', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1556249', 'DEACU George', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1556255', 'RATH Bogdan', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1559048', 'WIBERG Johanna', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1559066', 'FORSBERG Thomas', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1559067', 'AXNER Tomas', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1561282', 'da ROCHA Cristiano', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1562563', 'SOLBERG Glenn', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1562564', 'SVENSSON Tomas', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1562566', 'APELGREN Michael', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1562963', 'WINIARSKI Michal', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1562973', 'RANNER Thomas', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1562974', 'POSMYK Dominik', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1564287', 'QUSAI MUNIR', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1564321', 'CRUZ LOPEZ Jose L', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1564323', 'COLON Nelson', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1564325', 'CRUZ Rafael', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1565143', 'MLADENOVA Albena', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1565672', 'ROTAN Ruslan', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1568648', 'GOJKOVIC Vladimir', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1572650', 'ROUSSEAUX Emile', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1572652', 'ANDRE Felix', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1572654', 'GAUTHIER Charles', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1573466', 'TOUPANE Jean Aime', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1573467', 'MELAIN Catherine', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1573668', 'COLLET Vincent', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1573669', 'DONNADIEU Pascal', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1573670', 'ATKINSON Kenny', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1574076', 'CIAMARRA Roberto', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1574080', 'GEILER Loic', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1574082', 'GIANI Andrea', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1878950', 'SANTARELLI Daniele', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1878952', 'FLISI Diego', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1878956', 'ZOTTA Andrea', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1879044', 'VATANSEVER Recep', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1879645', 'DARET Jerome', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1879871', 'KRUMBHOLZ Olivier', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1879872', 'GARDILLOU Sebastien', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1879875', 'LEYNAUD Amandine', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1880388', 'MWEMA Kevin', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1880389', 'AMONDE Andrew', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1880390', 'KISIA Louis', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1880620', 'HRUBESCH Horst', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1880626', 'CARLSON Britta', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1880629', 'FUCHS Michael', 'M', 'Goalkeeper Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1880639', 'NOERENBERG Thomas', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1888131', 'PAKKAN Saim', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1888242', 'IKEDA Futoshi', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1888372', 'ERSIMSEK Ahmetcan', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1891653', 'NAGANUMA Atsushi', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1891659', 'HAZUI Shota', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1891667', 'SHIOTA Yoshinori', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1891686', 'KASHIMA Tomoyo', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1891688', 'NAKAJIMA Takako', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1892047', 'KAPADZE Timur', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1893216', 'GILLE Guillaume', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1893217', 'MATHE Erick', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1894657', 'WILLE Jonas', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1894659', 'EGE Steinar', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1894661', 'BOQUIST Martin', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1894662', 'OLSSON Mats', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1894663', 'HERGEIRSSON Thorir', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1894666', 'LARSEN Tonje', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1895269', 'BRUUN Michael', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1895270', 'JOERGENSEN Lars', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1895275', 'KRONBORG Henrik', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1895276', 'JACOBSEN Nikolaj', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1895279', 'JENSEN Jesper', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1896562', 'PARECKI Antoni Jerzy', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1896698', 'SNYMAN Philip', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1896700', 'LUCKAN Ghafoer', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1897292', 'BLECHER SIDOROVA Svetlana', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1897518', 'ZAITSEVA Olesia', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1897752', 'KHOLOD Maryna', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1897904', 'KIM Hyou Mi', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1898540', 'LAI Yawen', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1898944', 'HERBERT Gordie', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1898950', 'THOMAIDIS Lisa', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1898951', 'PARSONS Sidney', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1898953', 'MEADOWS Clarissa', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1898959', 'PERWAS Klaus', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1898962', 'HERBERT Daniel', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1899285', 'WUDTKE Erik', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1899286', 'BEPPLER Jochen', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1899289', 'ANDERSSON Mattias', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1899294', 'GISLASON Alfred', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1899296', 'GAUGISCH Markus', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1899298', 'JANKOVIC Jasmina', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1900728', 'HENRY Thierry', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1900729', 'BATICLE Gerald', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1900730', 'CLICHY Gael', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1900731', 'JANOT Jeremie', 'M', 'Goalkeeper Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901253', 'PEREIRA BRAVO Joao', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901258', 'SAMMELVUO Tuomas', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901261', 'HAWKINS Michael', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901805', 'ZHENG Wei', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901818', 'RUPEREZ Cesar', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901836', 'SUZUKI Yoshikazu', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901839', 'ONZUKA Toru', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901849', 'GAINES Corey', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1901850', 'HOVASSE Tom', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1902914', 'RUSEK Pawel', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1902918', 'GRBIC Nikola', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1902919', 'SWACZYNA Adam', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903371', 'MATOSEVIC Valter', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903379', 'SIGURDSSON Dagur', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903381', 'SPOLJARIC Denis', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903707', 'ABDELFATTAH Aziza', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903722', 'MOHAMED Mai', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903754', 'LATIF Yasmine', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903771', 'FABRE Julie', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903772', 'OBRY Laure', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903833', 'LORENT Jill', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1903900', 'RECKINGER Xavier', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1906448', 'LORANTOS Theodoros', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1906454', 'DERENTY Lorene', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1906462', 'BRUZZO Florian', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1906468', 'KOBESCAK Vjekoslav', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908234', 'MENDEZ Marcelo', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908241', 'LOPEZ Martin', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908245', 'RICO GOLBA Pablo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908401', 'ARROYO Gavin', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908402', 'UDOVICIC Dejan', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908403', 'USTASZEWSKI Matt', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908408', 'CAHILL Molly', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908409', 'KRIKORIAN Adam', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908410', 'OEDING Chris', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908649', 'KWIEK Marcos', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908654', 'ROCHA PACHECO Wagner', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908776', 'YAMAMOTO Hayato', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908788', 'AMOR Simon Daniel Edward', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908796', 'SUZUKI Takashi', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908800', 'SAKATA Takahiro', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908801', 'UMEDA Koichi', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908804', 'KANEMATSU Yuka', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908808', 'SANCHEZ DURAN Wilson', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908861', 'ZHANG Xiaohuan', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908862', 'WANG Jiuli', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1908865', 'TARRES CAMPA Ana', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1909923', 'ELNAFRAWY Mohamed', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1911256', 'ARZA Carlos Vivier', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1912238', 'CATITO Nelson', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1913681', 'CAI Bin', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1913682', 'LI Yanlong', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1913683', 'YUAN Zhi', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1915796', 'TUCAK Ivica', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1915797', 'POSINKOVIC Renco', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1915807', 'MARELJA Jure', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1915986', 'COURTEIX David', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1915987', 'IGARZA Germain', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1917164', 'DIALLO Badara Alou', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1917720', 'DUNPHY Marv', 'M', '2nd Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1917721', 'KIRALY Karch', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1917722', 'MIYASHIRO Tama', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1917723', 'REFT Alfee', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1917725', 'VIRTUE Erin', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918016', 'FUERBRINGER Matt', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918018', 'SPERAW John', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918019', 'WEBER Javi', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918026', 'WALL Mike', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918543', 'TOKUMOTO Yukito', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918556', 'BLAIN Philippe', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918560', 'FUKATSU Takayuki', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918568', 'ITOH Kenji', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918571', 'MANABE Masayoshi', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1918572', 'KAWAKITA Gen', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1921141', 'de GIORGI Ferdinando', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1921142', 'CAPONERI Massimo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1921143', 'GIOLITO Nicola', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1921148', 'VELASCO Julio', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1921149', 'BARBOLINI Massimo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1921150', 'BERNARDI Lorenzo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1924891', 'DUGONJIC Ivo Martin', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1924892', 'PUIG CARPANETO Gabriel', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1925565', 'CAMPAGNA Alessandro', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1925566', 'SILIPO Carlo', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1925568', 'FARINELLI Roberta', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1925590', 'POMILIO Amedeo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1925602', 'GIALLOMBARDO Patrizia', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1925620', 'di CECCA Cosimino', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1926601', 'MACKINTOSH Euan', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1926602', 'SWEENEY Cory', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1926603', 'GIBBS Rodney', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1926604', 'COCKER Edwin', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1926605', 'CAMA Tomasi', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1926606', 'ROSS Stu', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1926607', 'MURPHY Amanda', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1926612', 'McMASTER Travis', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1927222', 'LU Zhuan', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1927223', 'PASQUALETTI Massimo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1927270', 'GOMEZ AGUERA Salvador Emilio', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1927271', 'JANE GIRALT Juan', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1927274', 'WU Zhiyu', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1927873', 'LARHOLM Erik Jonas', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1927879', 'RADIC Vanja', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1927880', 'SIGNELL Kurt Henrik', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1928154', 'MWAPE Bruce', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1928466', 'LAVARINI Stefano', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1928467', 'VETTORI Nicola', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1928468', 'PACHLINSKI Krystian', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1928469', 'SUFA Bartosz', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1928714', 'NTHALA Charity', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1929717', 'ALFARO RODRIGUEZ Santiago', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1930168', 'RENARD Herve', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1930666', 'PHIRI Yona', 'M', 'Goalkeeper Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1930922', 'ABARCA Megan', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1931463', 'MWILA Florence', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1931488', 'ELFAKHARANY Hany', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1931494', 'SIERRA MENDEZ Jose Manuel', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1931502', 'PASTOR GOMEZ Juan Carlos', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1932176', 'RODRIGUEZ VAQUERO Jose Maria', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1932535', 'VELASCO ENCINAS Miguel Angel', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1933362', 'GOLOVIN Vlagyimir Alekszandrovics', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1933372', 'PIGNICZKI Krisztina', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1933474', 'MASCHERANO Javier', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1933569', 'MARSIGLIA Angelo', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1934811', 'PEREZ Carlos', 'M', 'Goalkeeper Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1934833', 'DAZEL Renfred', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1934834', 'MOLOPYANE Obakeng', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1934837', 'AFRIKA Cecil', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1935326', 'WAKAMA Rena', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1935667', 'FUENTES Andrea', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1935669', 'TEIXEIRA Lara', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1936918', 'PABLO Jose', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1940074', 'GOORJIAN Brian', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1940075', 'CHAMBERS Cheryl', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1940088', 'NIELSEN Matt', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1940093', 'BRONDELLO Sandy', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1940331', 'PYSMENNA Oksana', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1940930', 'CSEH Sandor Viktor', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1941188', 'MUNALA Japheth', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1941189', 'BARASA James', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1941198', 'MIHOK Attila', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1942626', 'DENIA Santi', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1942806', 'McLEOD Shane', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1942828', 'VARGA Zsolt', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1943302', 'HAYES Emma', 'F', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1943308', 'REDDY Denise', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1943311', 'SEARLE Stuart', 'M', 'Goalkeeper Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1943842', 'JARA SAGUIER Carlos', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944188', 'COVELO Alex', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944189', 'MITROVIC Marko', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944190', 'PAYNE Russell', 'M', 'Goalkeeper Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944191', 'SEGARES Gonzalo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944971', 'MAYNE Michael', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944973', 'BAZELEY Darren', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944974', 'GOTHARD Paul', 'M', 'Goalkeeper Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944977', 'READINGS Tony', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1944979', 'ELLIOTT Simon', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1945447', 'MURRAY Emma', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1947623', 'YANITSAS Andrew', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1947628', 'DENIS Eddie', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1947636', 'RIPPON Bec', 'F', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1947637', 'WOODS Taryn', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1947638', 'HAMILL Tim', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948319', 'MARTIN CEDRES Ambrosio Jose', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948320', 'MONTES AGUERA Cesar Jesus', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948321', 'PRADES PONS Jose Ignacio', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948322', 'RIBERA ROMANS Jordi', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948431', 'KOSTIC Oliver', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948433', 'PESIC Svetislav', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948750', 'DRLJACA Ljubica', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948752', 'MALJKOVIC Marina', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948904', 'BEATTIE Ciaran', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948911', 'NOLAN James', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948914', 'RIDDELL Scott', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948979', 'JANIC Bojan', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948980', 'JEVTIC Ivica', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948981', 'KOLAKOVIC Igor', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1948983', 'MAJSTOROVIC Neven', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1949063', 'BLAGOJEVIC Jelena', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1949064', 'GUIDETTI Giovanni', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1949459', 'van den HEUVEL Michel', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1949874', 'MEZIANE Rachid', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950176', 'BARTON Emilee', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950180', 'STANNARD James', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950182', 'MANENTI John', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950187', 'WALSH Timothy', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950509', 'BYDWELL Emilie', 'F', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950510', 'TEST Zack', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950515', 'FORD Trey', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950520', 'FRIDAY Mike', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1950521', 'GREENING Phil', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1952532', 'SPLITTER Tiago', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1953170', 'OIWA Go', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1954482', 'KERR Steve', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1954483', 'LUE Tyronn', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1954484', 'SPOELSTRA Erik', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1954501', 'REEVE Cheryl', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1954502', 'TAYLOR Joni', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1954503', 'THIBAULT Mike', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1954672', 'KOLINISAU Ratu Osea', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1955000', 'ARENHART ALVES Ismael', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1955021', 'BRODERICK William', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1955881', 'NAMAUA Tikiko', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1955954', 'KLAMBURG ROQUE Paula', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1955958', 'ONO Shoko', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1956202', 'LUZON Guy', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1956472', 'BILIC Darko', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1956473', 'CIRIC Stefan', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1956476', 'STEVANOVIC Uros', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957027', 'ADEL MOSTAFA', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957190', 'FUJIKI Mayuko', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957191', 'JIMENEZ NIETO Cecilia', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957192', 'REQUENA PERICAS Judit', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957222', 'ANDREO GABAN Angel Luis', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957223', 'APARICIO SUNEN Antonio Francisco', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957224', 'IVANOV PIRALKOV Svilen', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957225', 'MARTIN LOZANO David', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957226', 'OCA GAIA Miguel Angel', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1957227', 'VALLS NART Jordi', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1958754', 'GUIL Luis', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1958756', 'MENDEZ Miguel', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1958758', 'REY Luis', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1958761', 'SANCHEZ CANETE CALVO Angel Luis', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1958763', 'SCARIOLO Sergio', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1960844', 'BARRIEAU Jocelyn', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1960845', 'HANRATTY Jack', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1960848', 'MONAGHAN Iain', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1960860', 'JOYCE Jenn', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1961586', 'VOLAVOLA Timoci', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1961912', 'FULI Saiasi', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1962265', 'TOPPING James', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1962452', 'TEMPLE-JONES Allan', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1963019', 'MICALE Rogerio', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1963175', 'TOME Montse', 'F', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1963627', 'LOPEZ ROMERO Victor Hugo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1963628', 'ORTEGA PEREZ Antonio Carlos', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1964423', 'ROCHA de REZENDE Bernardo', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1964448', 'RIBAS Giuliano', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1964453', 'LAGES GUIMARAES Jose Roberto', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1964473', 'DO REGO BARROS JUNIOR Paulo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1964481', 'LEONALDO Roberley Luiz', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1964485', 'TABACH Ricardo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1964492', 'COPPINI FERNANDES Wagner Luiz', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1967258', 'PRIESTMAN Bev', 'F', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1967332', 'LIMA Brian', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1967468', 'PARADELO David', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1967471', 'POSTERIVO Stefano', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1967472', 'CAMPBELL Cora', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1967683', 'ELIAS Arthur', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968210', 'LALOMILO Faamaoni', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968247', 'CIRKOVIC Vedran', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968453', 'CHERNETSKA Nataliya', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968484', 'KAMMENOU Alexia Anna', 'F', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968489', 'LEMPESIS Xenofon', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968491', 'PYRPYRIS Anastasios', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968492', 'SCHIZAS Anastasios', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968495', 'VLACHOS Theodoros', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968531', 'KANTZOURIS Ilias', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968540', 'SPANOULIS Vasilis', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968802', 'FJELLSTROM Jens', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968822', 'ANDREATTA Mel', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968838', 'GUSTAVSSON Tony', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968868', 'van ECK Richard', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1968871', 'DOUDESIS Eva', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1969357', 'SEKTIOUI Tarik', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1970317', 'CLARIJS Ricardo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1970322', 'JOHANSSON Per', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1970733', 'GOUTSEVA Anastasia', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1972461', 'JAUMA CAYUELA Esther', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1972933', 'GOMEZ Ibai', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1973524', 'MEIJER Eric', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1973525', 'KOSLOWSKI Felix', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1973532', 'FERRER CUTINO Gil', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1973576', 'IVEY Royal', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1974021', 'KULESZA Kasia', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1974022', 'MORGAN Kerri', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1974025', 'VOLOSHYNA Anna', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1974026', 'YAKHNO Yelyzaveta', 'F', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1974755', 'BAUR Steve', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1974756', 'BJORKGREN Nate', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1974760', 'FERNANDEZ Jordi', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1974766', 'LAPENA Victor', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1975398', 'DENG Luol', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1977388', 'WALDRUM Randy', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1977689', 'DIAWARA Kaba', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1978688', 'MUNOZ BENITEZ Fernando', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1980943', 'PAVLIC Aljaz', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1980962', 'MIJATOVIC Branka', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1980979', 'ADZIC Dragan', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1980987', 'CRETU Gheorghe', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1981325', 'ZVIZEJ Luka', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1981356', 'de CECCO Matteo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1981689', 'ZORMAN Uros', 'M', 'Head Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1981697', 'KEDACIC Zoran', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('1986732', 'MUGANGUZI Wani', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('3430822', 'PETROVIC Aleksandar', 'M', 'Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('3538853', 'DONNELLY Peter', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('3546458', 'DIAWARA Fousseni', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('3546645', 'CAUKAUNIVALU Setefano', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('4119109', 'ELZEFTAWEY Tarek', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('4646497', 'PROST KOSIR Primoz', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('4968917', 'QUESNEL Yannick', 'M', 'Goalkeeper Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230002', 'HERDEIRO Alvaro Francisco', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230003', 'MAROJA Gabriel Augusto', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230006', 'ALONSO BERNARDO Jessica', 'F', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230010', 'LARSSON Thomas Erik Daniel', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230012', 'CAROU Gonzalo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230013', 'CAZON Guillermo', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230017', 'CAAMANO Juan', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230018', 'TORRESCUSA Ignacio', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9230020', 'GJERDE Joar', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9430008', 'CICHELLO Juan Manuel', 'M', 'Assistant Coach');
INSERT INTO Coach (Coach_Code, Name, Gender, `Function`) VALUES ('9450042', 'VASSILIADES Emmanuel', 'M', 'Assistant Coach');
